blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.blog_home, name='blog_home'),
    path('<int:pk>/', views.blog_dtl, name='blog_dtl'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.


class blog(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField()
    description = models.TextField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

# Create your models here.

class project(models.Model):
    title = models.CharField(max_length=50)
    description = models.CharField(max_length=150)
    image = models.ImageField(upload_to='portfolio/images/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render,get_object_or_404
from . import models
# Create your views here.

def blog_home(request):
    blogs = models.blog.objects.all()
    return render(request, 'blog/blog_home.html', {'blogs':blogs})

def blog_dtl(request, pk):
    blog = get_object_or_404(models.blog, pk=pk)
    return render(request, 'blog/blog_dtl.html', {'blog':blog})

portfolio/views.py
from django.shortcuts import render
from . import models
# Create your views here.

def home(request):
    contents = models.project.objects.all()
    return render(request,'portfolio/home.html',{'contents': contents})

blog/templates/blog/blog_dtl.html
{% extends "base.html" %}
{% block content %}
<div class="container">
  <h2 class="text-center mt-5" id="blogdetailtitle">{{blog.title}}</h2>
  <h3 class="text-center text-muted mb-5">--{{blog.date}}--</h3>
  <p>{{blog.description|safe}}</p>
</div>
{% endblock %}

blog/templates/blog/blog_home.html
{% extends "base.html" %}
{% block content %}
    <h1 id="blogtitle" class="font-weight-bold text-center">Blog</h1>
    <h3 class="text-center mb-5">written {{blogs.count}} blog{{ blogs.count|pluralize }}</h3>
    {% for blog in blogs %}
    <div class="row justify-content-center my-3">
      <div class="col-md-10">
        <a href="{% url "blog:blog_dtl" pk=blog.pk%}"><h3>{{blog.title}}</h3></a>
        <h4>{{blog.date}}</h4>
        <h4>{{blog.description|truncatechars:50}}</h4>
      </div>
    </div>
    {% endfor %}
{% endblock %}

portfolio/templates/portfolio/home.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container">
      <h1>Welcome To My World</h1>
      <div class="row justify-content-center my-3">
        <div class="col-5">
          <img src="{% static "portfolio/batman.jpg" %}" class="img-fluid">
        </div>
      </div>
      <div class="row justify-content-center mb-3">
        <div class="col-md-8 text-center">
          <h1 id="hometext" class="font-weight-bold">Full Stack Developer</h1>
        </div>
      </div>
        <div class="row">
            {% for content in contents %}
            <div class="col-lg-4 col-md-6">
              <h2>{{content.title}}</h2>
              <p>{{content.description}}</p>
              <a href={{content.url}}><img src={{content.image.url}} class="img-fluid mb-2"></a>
            </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>portfolio</title>
    <link rel="icon" type="image/png" href="{% static "logo.png" %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static "custom.css" %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="{% url "home" %}">
    <img src="{% static "logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Logo">
    <span>Nihal Latheef</span>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse text-center" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="{% url "blog:blog_home" %}">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link " href="{% static "portfolio/CV.pdf" %}">Resume</a>
      </li>
    </ul>
  </div>
</nav>
{% block content %}
{% endblock %}
  </body>
</html>